server {
    listen 80;
    server_name www.heliospressing.com;
    return 301 $scheme://heliospressing.com$request_uri;
}

server {
    listen 80;
    server_name heliospressing.com;

    location / {
        proxy_pass http://127.0.0.1:3333;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /assets/ {
        alias /opt/apps/helios-api/public/assets/;
        access_log off;
        expires 30d;
    }

    location ^~ /.git/ {
        return 404;
        deny all;
    }
}